### ISSUE TITLE
CSV.read is overwriting a method in base on 0.4.1

### ISSUE THREAD

**Issue by amellnik** [JuliaDB/CSV.jl#16]
```
WARNING: Method definition read(Base.AbstractIOBuffer, Type{UInt8}) in module Base
 overwritten in module CSV at C:\Users\amellnik\.julia\v0.4\CSV\src\Source.jl:13.
```

It looks like the base method was recently added: https://github.com/JuliaLang/julia/commit/bb744fd14f01223961b0d2c74229a0ce001872e5

**Comment by maximsch2** [comment]
Moreover, a built-in method is checking for EOF, while a local version is not

**Comment by quinnj** [comment]
the reason for overwriting is because the usage of `Base.read` in the CSV code is tightly controlled and the EOF checking are redundant (i.e. we're already manually checking for EOF). I think, unfortunately, we may just need to roll our own quick IOBuffer type to get the speed we should be getting here.
