### ISSUE TITLE
Error parsing Netflix Prize data

### ISSUE THREAD

**Issue by jiahao** [JuliaDB/CSV.jl#19]
A typical CSV file from the Netflix Prize data set looks like:

```csv
3884821:
249897724,2,2001-11-26
483,3,2000-01-13
4875839,5,2059-07-27
```

and so on.

Reading this snippet into CSV throws an error:

```jl
julia> CSV.csv("test.txt")
ERROR: CSV.CSVError("error parsing a `Int64` value on column 1, row 3; encountered '-'")
 in parsefield at /Users/test/.julia/v0.4/CSV/src/getfields.jl:86
 in parsefield! at /Users/test/.julia/v0.4/CSV/src/Source.jl:216
 in stream! at /Users/test/.julia/v0.4/CSV/src/Source.jl:230
 in stream! at /Users/test/.julia/v0.4/DataStreams/src/DataStreams.jl:243
 in csv at /Users/test/.julia/v0.4/CSV/src/Source.jl:284
```

**Comment by quinnj** [comment]
Fixed by specifying header details, i.e.:
```julia
CSV.csv("test.txt"; header=0, datarow=2)
```
The `header` keyword can be an integer, meaning the row where the column names are define; a range, meaning the *rows* where the column names are defined (for multi row column names); or a string vector, in which the user is providing the column names themselves. Note that `header=0` is a special case where the user is specifying that *no* header exists in the file, and column names will then be auto-generated.
